<?php
/**
 * @var Planet_Pay_Block_Adminhtml_Order_View_Handling_Request $this
 */
?>
<div id="order_request_block">
    <div id="handling_form" class="order-handling-form">
        <div><?php echo Mage::helper('planet_pay')->__('') ?></div>
        <div class="f-left">
            <?php echo $this->getChildHtml('submit_button') ?>
        </div>
        <div class="f-right">
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <ul class="note-list">
    <?php foreach ($this->getOrderRequestLogs() as $orderRequest): ?>
        <li>
            <strong><?php echo $this->helper('core')->formatDate($orderRequest->getDate(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($orderRequest->getDate(), 'medium') ?><span class="separator">|</span><strong><?php echo $orderRequest->getCode(); ?></strong><br/>
            <small>
                <?php echo $this->helper('planet_pay')->__('Order Request Status: ') ?>
                <strong class="subdue">
                    <?php if ($orderRequest->getSuccess()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                        <?php echo $this->helper('planet_pay')->__('Success') ?>
                    <?php else: ?>
                        <?php echo $this->helper('planet_pay')->__('Unsuccess') ?>
                    <?php endif; ?>
                </strong>
            </small>
            <br/>
            <?php
                echo $orderRequest->getDescription();
                if ($orderRequest->getCode() == '000.400.102') {
                    $order = $this->getOrder();
                    $email = $order->getCustomerEmail();
                    echo '<br /><a class="planet_customer_email" href="mailto:'.$email.'">'.$email.'</a>';
                }
            ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
