<?php
/** @var $this Planet_Pay_Block_Adminhtml_Order_View_Request */
?>
<table cellspacing="0" class="form-list">
    <?php foreach ($this->getOrderRequestCriterionData() as $criterionField): ?>
    <tr>
        <td class="label"><label><?php echo $criterionField['name']; ?></label></td>
        <td class="value"><strong><?php echo $criterionField['value']; ?></strong></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php foreach ($this->getOrderRequestOrderItems() as $id => $orderItem): ?>
    <h5> Order Item <?php echo $id; ?> </h5>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
        <?php foreach ($orderItem as $orderItemField): ?>
            <tr>
                <td class="label"><label><?php echo $orderItemField['name']; ?></label></td>
                <td class="value"><strong><?php echo $orderItemField['value']; ?></strong></td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
<?php endforeach; ?>
