<?php
/** @var $this Planet_Pay_Block_Adminhtml_Order_View_Request */
?>
<!--<div class="fieldset">-->
    <table cellspacing="0" class="form-list">
        <?php foreach ($this->getOrderRequestOptions() as $option): ?>
        <tr>
            <td class="label"><label><?php echo $option['name']; ?></label></td>
            <td class="value"><strong><?php echo $option['value']; ?></strong></td>
        </tr>
        <?php endforeach; ?>
    </table>
<!--</div>-->