<?php
$paymentCode = Mage::getSingleton('checkout/session')->getQuote()->getPayment()->getMethodInstance()->getCode();
$token = Mage::getSingleton('core/session')->getGenerateToken();
Mage::log($token);
$addJs = null;
if ($paymentCode != 'planet_pay') {
    $addJs = 'onclick="review.save();"';
?>
<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" <?php echo $addJs; ?>"><span><span><?php echo $this->__('Place Order') ?></span></span></button>

<?php } else{ ?>
<form  target="my_iframe" action="https://test.oppwa.com/v1/checkouts/<?php echo $token; ?>/payment" method="POST"> 
   <input type="submit" value="<?php echo $this->__('Place Order') ?>" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="show_review_processing(this);" style="clear: both;float:right;background-color:#FF7B2F;color:white;" />
   <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Processing please wait...') ?>" title="<?php echo $this->__('Processing please wait...') ?>" class="v-middle" /> <?php echo $this->__('Processing please wait...') ?>
        </span>
<iframe name="my_iframe" style="visibility: hidden"></iframe>

<?php } ?>
